name: "Generate release notes"
description: "generate release notes and comment to release issue"
author: "azutake"
inputs:
  base:
    required: true
    description: "base branch name"
  head:
    required: true
    description: "head branch name"
  test-procedure-comment:
    required: false
    default: "false"
    description: "is comment test procedure"
  #comment-template:
  #  required: false
  #  description: "template markdown file"
  token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
